# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HMI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HMID(object):
    def setupUi(self, HMID):
        HMID.setObjectName("HMID")
        HMID.resize(1008, 777)
        self.controlpnl = QtWidgets.QListView(HMID)
        self.controlpnl.setGeometry(QtCore.QRect(30, 60, 281, 641))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.controlpnl.setFont(font)
        self.controlpnl.setAutoFillBackground(False)
        self.controlpnl.setObjectName("controlpnl")
        self.connectCheck = QtWidgets.QPushButton(HMID)
        self.connectCheck.setGeometry(QtCore.QRect(90, 620, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.connectCheck.setFont(font)
        self.connectCheck.setObjectName("connectCheck")
        self.label = QtWidgets.QLabel(HMID)
        self.label.setGeometry(QtCore.QRect(90, 180, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.slideMotor = QtWidgets.QSlider(HMID)
        self.slideMotor.setGeometry(QtCore.QRect(90, 580, 160, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.slideMotor.setFont(font)
        self.slideMotor.setOrientation(QtCore.Qt.Horizontal)
        self.slideMotor.setObjectName("slideMotor")
        self.selectalgrtm = QtWidgets.QComboBox(HMID)
        self.selectalgrtm.setGeometry(QtCore.QRect(110, 210, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.selectalgrtm.setFont(font)
        self.selectalgrtm.setObjectName("selectalgrtm")
        icon = QtGui.QIcon.fromTheme("dark")
        self.selectalgrtm.addItem(icon, "")
        self.selectalgrtm.addItem("")
        self.selectalgrtm.addItem("")
        self.labelcontrol = QtWidgets.QLabel(HMID)
        self.labelcontrol.setGeometry(QtCore.QRect(120, 70, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelcontrol.setFont(font)
        self.labelcontrol.setObjectName("labelcontrol")
        self.executeCommand = QtWidgets.QPushButton(HMID)
        self.executeCommand.setGeometry(QtCore.QRect(90, 660, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.executeCommand.setFont(font)
        self.executeCommand.setObjectName("executeCommand")
        self.label_3 = QtWidgets.QLabel(HMID)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.figPlot = QtWidgets.QListView(HMID)
        self.figPlot.setGeometry(QtCore.QRect(340, 10, 401, 41))
        self.figPlot.setObjectName("figPlot")
        self.label_2 = QtWidgets.QLabel(HMID)
        self.label_2.setGeometry(QtCore.QRect(90, 250, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(HMID)
        self.comboBox.setGeometry(QtCore.QRect(110, 280, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.manualEdit = QtWidgets.QLineEdit(HMID)
        self.manualEdit.setGeometry(QtCore.QRect(130, 520, 61, 21))
        self.manualEdit.setObjectName("manualEdit")
        self.label_5 = QtWidgets.QLabel(HMID)
        self.label_5.setGeometry(QtCore.QRect(200, 520, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(HMID)
        self.label_6.setGeometry(QtCore.QRect(140, 490, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(HMID)
        self.radioButton.setGeometry(QtCore.QRect(150, 550, 51, 17))
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(HMID)
        self.checkBox.setGeometry(QtCore.QRect(120, 460, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.plotwdgt = QtWidgets.QWidget(HMID)
        self.plotwdgt.setGeometry(QtCore.QRect(330, 60, 611, 341))
        self.plotwdgt.setObjectName("plotwdgt")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.plotwdgt)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(HMID)
        self.label_7.setGeometry(QtCore.QRect(130, 320, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.amplitudeSpeed = QtWidgets.QLineEdit(HMID)
        self.amplitudeSpeed.setGeometry(QtCore.QRect(140, 350, 61, 21))
        self.amplitudeSpeed.setObjectName("amplitudeSpeed")
        self.label_8 = QtWidgets.QLabel(HMID)
        self.label_8.setGeometry(QtCore.QRect(150, 390, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.amplitudeSpeed_2 = QtWidgets.QLineEdit(HMID)
        self.amplitudeSpeed_2.setGeometry(QtCore.QRect(140, 420, 61, 21))
        self.amplitudeSpeed_2.setObjectName("amplitudeSpeed_2")
        self.controlParam = QtWidgets.QGraphicsView(HMID)
        self.controlParam.setGeometry(QtCore.QRect(380, 530, 521, 171))
        self.controlParam.setObjectName("controlParam")
        self.label_9 = QtWidgets.QLabel(HMID)
        self.label_9.setGeometry(QtCore.QRect(270, 580, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(HMID)
        self.label_10.setGeometry(QtCore.QRect(60, 580, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(HMID)
        self.label_11.setGeometry(QtCore.QRect(560, 500, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(HMID)
        self.line_2.setGeometry(QtCore.QRect(630, 530, 20, 171))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(HMID)
        self.label_4.setGeometry(QtCore.QRect(100, 100, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.actualRPM = QtWidgets.QLCDNumber(HMID)
        self.actualRPM.setGeometry(QtCore.QRect(120, 130, 111, 41))
        self.actualRPM.setObjectName("actualRPM")
        self.label_12 = QtWidgets.QLabel(HMID)
        self.label_12.setGeometry(QtCore.QRect(460, 540, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(HMID)
        self.label_13.setGeometry(QtCore.QRect(720, 540, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.proportionalGain = QtWidgets.QLineEdit(HMID)
        self.proportionalGain.setGeometry(QtCore.QRect(490, 579, 41, 21))
        self.proportionalGain.setObjectName("proportionalGain")
        self.label_14 = QtWidgets.QLabel(HMID)
        self.label_14.setGeometry(QtCore.QRect(460, 580, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(HMID)
        self.label_15.setGeometry(QtCore.QRect(460, 621, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.integralGain = QtWidgets.QLineEdit(HMID)
        self.integralGain.setGeometry(QtCore.QRect(490, 620, 41, 21))
        self.integralGain.setObjectName("integralGain")
        self.label_16 = QtWidgets.QLabel(HMID)
        self.label_16.setGeometry(QtCore.QRect(460, 661, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.derivativeGain = QtWidgets.QLineEdit(HMID)
        self.derivativeGain.setGeometry(QtCore.QRect(490, 660, 41, 21))
        self.derivativeGain.setObjectName("derivativeGain")
        self.label_17 = QtWidgets.QLabel(HMID)
        self.label_17.setGeometry(QtCore.QRect(720, 581, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.discountRate = QtWidgets.QLineEdit(HMID)
        self.discountRate.setGeometry(QtCore.QRect(810, 580, 41, 21))
        self.discountRate.setObjectName("discountRate")
        self.learningRate = QtWidgets.QLineEdit(HMID)
        self.learningRate.setGeometry(QtCore.QRect(810, 619, 41, 21))
        self.learningRate.setObjectName("learningRate")
        self.label_18 = QtWidgets.QLabel(HMID)
        self.label_18.setGeometry(QtCore.QRect(720, 620, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.episodeNum = QtWidgets.QLineEdit(HMID)
        self.episodeNum.setGeometry(QtCore.QRect(810, 659, 41, 21))
        self.episodeNum.setObjectName("episodeNum")
        self.label_19 = QtWidgets.QLabel(HMID)
        self.label_19.setGeometry(QtCore.QRect(710, 660, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.figPlot.raise_()
        self.controlpnl.raise_()
        self.connectCheck.raise_()
        self.label.raise_()
        self.slideMotor.raise_()
        self.selectalgrtm.raise_()
        self.labelcontrol.raise_()
        self.executeCommand.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.manualEdit.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.radioButton.raise_()
        self.checkBox.raise_()
        self.plotwdgt.raise_()
        self.label_7.raise_()
        self.amplitudeSpeed.raise_()
        self.label_8.raise_()
        self.amplitudeSpeed_2.raise_()
        self.controlParam.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.line_2.raise_()
        self.label_4.raise_()
        self.actualRPM.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.proportionalGain.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.integralGain.raise_()
        self.label_16.raise_()
        self.derivativeGain.raise_()
        self.label_17.raise_()
        self.discountRate.raise_()
        self.learningRate.raise_()
        self.label_18.raise_()
        self.episodeNum.raise_()
        self.label_19.raise_()

        self.retranslateUi(HMID)
        QtCore.QMetaObject.connectSlotsByName(HMID)

    def retranslateUi(self, HMID):
        _translate = QtCore.QCoreApplication.translate
        HMID.setWindowTitle(_translate("HMID", "Dialog"))
        self.connectCheck.setText(_translate("HMID", "Check Connection"))
        self.label.setText(_translate("HMID", "Select The Control Algorithm"))
        self.selectalgrtm.setItemText(0, _translate("HMID", "PID"))
        self.selectalgrtm.setItemText(1, _translate("HMID", "PID Anti Windup"))
        self.selectalgrtm.setItemText(2, _translate("HMID", "Q Learning"))
        self.labelcontrol.setText(_translate("HMID", "Control Panel"))
        self.executeCommand.setText(_translate("HMID", "Compile and Execute"))
        self.label_3.setText(_translate("HMID", "DC Motor Control Simple Human Machine Interface"))
        self.label_2.setText(_translate("HMID", "Adjust The Reference Signal"))
        self.comboBox.setItemText(0, _translate("HMID", "Unit Step"))
        self.comboBox.setItemText(1, _translate("HMID", "Manual Control"))
        self.comboBox.setItemText(2, _translate("HMID", "Square"))
        self.comboBox.setItemText(3, _translate("HMID", "Sinusoidal"))
        self.comboBox.setItemText(4, _translate("HMID", "Random"))
        self.manualEdit.setText(_translate("HMID", "0"))
        self.label_5.setText(_translate("HMID", "RPM"))
        self.label_6.setText(_translate("HMID", "Speed Target"))
        self.radioButton.setText(_translate("HMID", "Slider"))
        self.checkBox.setText(_translate("HMID", "Manual Control"))
        self.label_7.setText(_translate("HMID", "Amplitude (RPM)"))
        self.amplitudeSpeed.setText(_translate("HMID", "0"))
        self.label_8.setText(_translate("HMID", "Period (s)"))
        self.amplitudeSpeed_2.setText(_translate("HMID", "0"))
        self.label_9.setText(_translate("HMID", "64"))
        self.label_10.setText(_translate("HMID", "-64"))
        self.label_11.setText(_translate("HMID", "Control Parameter Adjustments"))
        self.label_4.setText(_translate("HMID", "Actual Motor Speed (RPM)"))
        self.label_12.setText(_translate("HMID", "PID Parameters"))
        self.label_13.setText(_translate("HMID", "Q Learning Parameters"))
        self.label_14.setText(_translate("HMID", "Kp ="))
        self.label_15.setText(_translate("HMID", "Ki ="))
        self.label_16.setText(_translate("HMID", "Kd ="))
        self.label_17.setText(_translate("HMID", "Discount Rate ="))
        self.label_18.setText(_translate("HMID", "Learning Rate ="))
        self.label_19.setText(_translate("HMID", "Episode Number ="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HMID = QtWidgets.QDialog()
    ui = Ui_HMID()
    ui.setupUi(HMID)
    HMID.show()
    sys.exit(app.exec_())

